name: github pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v1.2.0
        with:
          mdbook-version: 'latest'

      - run: cd ./debug && mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./debug/book
